name: Publish Docker image to GHCR

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
      - '*.*.*'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/karakeep
          tags: |
            type=ref,event=branch,branch=main
            type=sha
            type=semver,pattern={{version}},prefix=

      - name: Build and push (AIO)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          target: aio
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

